CREATE TABLE IF NOT EXISTS USER(
   ID INTEGER    PRIMARY KEY       AUTOINCREMENT,
   LOGIN           CHAR(50)    NOT NULL,
   PASSWORD        CHAR(50)    NOT NULL,
   LAST_LOGIN      DATETIME DEFAULT NULL,
   CURRENT_DATE    DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS GAME_TYPE(
  ID INTEGER    PRIMARY KEY AUTOINCREMENT,
  GAME_TYPE      CHAR(50) NOT NULL
);

INSERT INTO GAME_TYPE (GAME_TYPE)
SELECT 'HOT_SEATS', 'VS_COMPUTER', 'THROUGH_NET'
WHERE NOT EXISTS (SELECT GAME_TYPE FROM GAME_TYPE)

CREATE TABLE IF NOT EXISTS RANKING(
     ID INTEGER    PRIMARY KEY AUTOINCREMENT,
     USERID        INTEGER,
     GAME_TYPE     INTEGER  NOT NULL,
     WIN           INT      DEFAULT 0,
     LOST          INT      DEFAULT 0,
     DRAW          INT      DEFAULT 0,
     CURRENT_DATE    DATETIME DEFAULT CURRENT_TIMESTAMP,
     FOREIGN KEY (USERID) REFERENCES USER(ID),
     FOREIGN KEY (GAME_TYPE) REFERENCES GAME_TYPE(ID)
);

